// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.2.0
//   protoc               v5.28.3
// source: lcu/gameflow.proto
/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
export var GameflowPhaseEnum;
(function (GameflowPhaseEnum) {
    /** Matchmaking - 正在匹配 */
    GameflowPhaseEnum[GameflowPhaseEnum["Matchmaking"] = 0] = "Matchmaking";
    /** ChampSelect - 英雄选择中 */
    GameflowPhaseEnum[GameflowPhaseEnum["ChampSelect"] = 1] = "ChampSelect";
    /** ReadyCheck - 等待接受状态中 */
    GameflowPhaseEnum[GameflowPhaseEnum["ReadyCheck"] = 2] = "ReadyCheck";
    /** InProgress - 游戏进行中 */
    GameflowPhaseEnum[GameflowPhaseEnum["InProgress"] = 3] = "InProgress";
    /** EndOfGame - 游戏结算 */
    GameflowPhaseEnum[GameflowPhaseEnum["EndOfGame"] = 4] = "EndOfGame";
    /** Lobby - 房间 */
    GameflowPhaseEnum[GameflowPhaseEnum["Lobby"] = 5] = "Lobby";
    /** GameStart - 游戏开始 */
    GameflowPhaseEnum[GameflowPhaseEnum["GameStart"] = 6] = "GameStart";
    /** None - 无 */
    GameflowPhaseEnum[GameflowPhaseEnum["None"] = 7] = "None";
    /** Reconnect - 重新连接 */
    GameflowPhaseEnum[GameflowPhaseEnum["Reconnect"] = 8] = "Reconnect";
    /** WaitingForStats - 等待结果 */
    GameflowPhaseEnum[GameflowPhaseEnum["WaitingForStats"] = 9] = "WaitingForStats";
    /** PreEndOfGame - 结束游戏之前 */
    GameflowPhaseEnum[GameflowPhaseEnum["PreEndOfGame"] = 10] = "PreEndOfGame";
    /** WatchInProgress - 在观战中 */
    GameflowPhaseEnum[GameflowPhaseEnum["WatchInProgress"] = 11] = "WatchInProgress";
    GameflowPhaseEnum[GameflowPhaseEnum["UNRECOGNIZED"] = -1] = "UNRECOGNIZED";
})(GameflowPhaseEnum || (GameflowPhaseEnum = {}));
export function gameflowPhaseEnumFromJSON(object) {
    switch (object) {
        case 0:
        case "Matchmaking":
            return GameflowPhaseEnum.Matchmaking;
        case 1:
        case "ChampSelect":
            return GameflowPhaseEnum.ChampSelect;
        case 2:
        case "ReadyCheck":
            return GameflowPhaseEnum.ReadyCheck;
        case 3:
        case "InProgress":
            return GameflowPhaseEnum.InProgress;
        case 4:
        case "EndOfGame":
            return GameflowPhaseEnum.EndOfGame;
        case 5:
        case "Lobby":
            return GameflowPhaseEnum.Lobby;
        case 6:
        case "GameStart":
            return GameflowPhaseEnum.GameStart;
        case 7:
        case "None":
            return GameflowPhaseEnum.None;
        case 8:
        case "Reconnect":
            return GameflowPhaseEnum.Reconnect;
        case 9:
        case "WaitingForStats":
            return GameflowPhaseEnum.WaitingForStats;
        case 10:
        case "PreEndOfGame":
            return GameflowPhaseEnum.PreEndOfGame;
        case 11:
        case "WatchInProgress":
            return GameflowPhaseEnum.WatchInProgress;
        case -1:
        case "UNRECOGNIZED":
        default:
            return GameflowPhaseEnum.UNRECOGNIZED;
    }
}
export function gameflowPhaseEnumToJSON(object) {
    switch (object) {
        case GameflowPhaseEnum.Matchmaking:
            return "Matchmaking";
        case GameflowPhaseEnum.ChampSelect:
            return "ChampSelect";
        case GameflowPhaseEnum.ReadyCheck:
            return "ReadyCheck";
        case GameflowPhaseEnum.InProgress:
            return "InProgress";
        case GameflowPhaseEnum.EndOfGame:
            return "EndOfGame";
        case GameflowPhaseEnum.Lobby:
            return "Lobby";
        case GameflowPhaseEnum.GameStart:
            return "GameStart";
        case GameflowPhaseEnum.None:
            return "None";
        case GameflowPhaseEnum.Reconnect:
            return "Reconnect";
        case GameflowPhaseEnum.WaitingForStats:
            return "WaitingForStats";
        case GameflowPhaseEnum.PreEndOfGame:
            return "PreEndOfGame";
        case GameflowPhaseEnum.WatchInProgress:
            return "WatchInProgress";
        case GameflowPhaseEnum.UNRECOGNIZED:
        default:
            return "UNRECOGNIZED";
    }
}
function createBasePhaseWithSummonerId() {
    return { phase: 0, summonerId: 0 };
}
export const PhaseWithSummonerId = {
    encode(message, writer = new BinaryWriter()) {
        if (message.phase !== 0) {
            writer.uint32(8).int32(message.phase);
        }
        if (message.summonerId !== 0) {
            writer.uint32(16).uint64(message.summonerId);
        }
        return writer;
    },
    decode(input, length) {
        const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
        let end = length === undefined ? reader.len : reader.pos + length;
        const message = createBasePhaseWithSummonerId();
        while (reader.pos < end) {
            const tag = reader.uint32();
            switch (tag >>> 3) {
                case 1:
                    if (tag !== 8) {
                        break;
                    }
                    message.phase = reader.int32();
                    continue;
                case 2:
                    if (tag !== 16) {
                        break;
                    }
                    message.summonerId = longToNumber(reader.uint64());
                    continue;
            }
            if ((tag & 7) === 4 || tag === 0) {
                break;
            }
            reader.skip(tag & 7);
        }
        return message;
    },
    fromJSON(object) {
        return {
            phase: isSet(object.phase) ? gameflowPhaseEnumFromJSON(object.phase) : 0,
            summonerId: isSet(object.summonerId) ? globalThis.Number(object.summonerId) : 0,
        };
    },
    toJSON(message) {
        const obj = {};
        if (message.phase !== 0) {
            obj.phase = gameflowPhaseEnumToJSON(message.phase);
        }
        if (message.summonerId !== 0) {
            obj.summonerId = Math.round(message.summonerId);
        }
        return obj;
    },
    create(base) {
        return PhaseWithSummonerId.fromPartial(base ?? {});
    },
    fromPartial(object) {
        const message = createBasePhaseWithSummonerId();
        message.phase = object.phase ?? 0;
        message.summonerId = object.summonerId ?? 0;
        return message;
    },
};
export const GamePhaseSharingServiceName = "lcu.gameflow.GamePhaseSharing";
export class GamePhaseSharingClientImpl {
    rpc;
    service;
    constructor(rpc, opts) {
        this.service = opts?.service || GamePhaseSharingServiceName;
        this.rpc = rpc;
    }
}
function longToNumber(int64) {
    const num = globalThis.Number(int64.toString());
    if (num > globalThis.Number.MAX_SAFE_INTEGER) {
        throw new globalThis.Error("Value is larger than Number.MAX_SAFE_INTEGER");
    }
    if (num < globalThis.Number.MIN_SAFE_INTEGER) {
        throw new globalThis.Error("Value is smaller than Number.MIN_SAFE_INTEGER");
    }
    return num;
}
function isSet(value) {
    return value !== null && value !== undefined;
}
