// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.2.0
//   protoc               v5.28.3
// source: lcu/lobby.proto
/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
function createBaseSimpleLocalMember() {
    return { isLeader: false, summonerId: 0 };
}
export const SimpleLocalMember = {
    encode(message, writer = new BinaryWriter()) {
        if (message.isLeader !== false) {
            writer.uint32(8).bool(message.isLeader);
        }
        if (message.summonerId !== 0) {
            writer.uint32(16).int64(message.summonerId);
        }
        return writer;
    },
    decode(input, length) {
        const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
        let end = length === undefined ? reader.len : reader.pos + length;
        const message = createBaseSimpleLocalMember();
        while (reader.pos < end) {
            const tag = reader.uint32();
            switch (tag >>> 3) {
                case 1:
                    if (tag !== 8) {
                        break;
                    }
                    message.isLeader = reader.bool();
                    continue;
                case 2:
                    if (tag !== 16) {
                        break;
                    }
                    message.summonerId = longToNumber(reader.int64());
                    continue;
            }
            if ((tag & 7) === 4 || tag === 0) {
                break;
            }
            reader.skip(tag & 7);
        }
        return message;
    },
    fromJSON(object) {
        return {
            isLeader: isSet(object.isLeader) ? globalThis.Boolean(object.isLeader) : false,
            summonerId: isSet(object.summonerId) ? globalThis.Number(object.summonerId) : 0,
        };
    },
    toJSON(message) {
        const obj = {};
        if (message.isLeader !== false) {
            obj.isLeader = message.isLeader;
        }
        if (message.summonerId !== 0) {
            obj.summonerId = Math.round(message.summonerId);
        }
        return obj;
    },
    create(base) {
        return SimpleLocalMember.fromPartial(base ?? {});
    },
    fromPartial(object) {
        const message = createBaseSimpleLocalMember();
        message.isLeader = object.isLeader ?? false;
        message.summonerId = object.summonerId ?? 0;
        return message;
    },
};
function createBaseSimpleLobbyInfo() {
    return { partyId: "", memberMap: {} };
}
export const SimpleLobbyInfo = {
    encode(message, writer = new BinaryWriter()) {
        if (message.partyId !== "") {
            writer.uint32(10).string(message.partyId);
        }
        Object.entries(message.memberMap).forEach(([key, value]) => {
            SimpleLobbyInfo_MemberMapEntry.encode({ key: key, value }, writer.uint32(18).fork()).join();
        });
        return writer;
    },
    decode(input, length) {
        const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
        let end = length === undefined ? reader.len : reader.pos + length;
        const message = createBaseSimpleLobbyInfo();
        while (reader.pos < end) {
            const tag = reader.uint32();
            switch (tag >>> 3) {
                case 1:
                    if (tag !== 10) {
                        break;
                    }
                    message.partyId = reader.string();
                    continue;
                case 2:
                    if (tag !== 18) {
                        break;
                    }
                    const entry2 = SimpleLobbyInfo_MemberMapEntry.decode(reader, reader.uint32());
                    if (entry2.value !== undefined) {
                        message.memberMap[entry2.key] = entry2.value;
                    }
                    continue;
            }
            if ((tag & 7) === 4 || tag === 0) {
                break;
            }
            reader.skip(tag & 7);
        }
        return message;
    },
    fromJSON(object) {
        return {
            partyId: isSet(object.partyId) ? globalThis.String(object.partyId) : "",
            memberMap: isObject(object.memberMap)
                ? Object.entries(object.memberMap).reduce((acc, [key, value]) => {
                    acc[globalThis.Number(key)] = SimpleLocalMember.fromJSON(value);
                    return acc;
                }, {})
                : {},
        };
    },
    toJSON(message) {
        const obj = {};
        if (message.partyId !== "") {
            obj.partyId = message.partyId;
        }
        if (message.memberMap) {
            const entries = Object.entries(message.memberMap);
            if (entries.length > 0) {
                obj.memberMap = {};
                entries.forEach(([k, v]) => {
                    obj.memberMap[k] = SimpleLocalMember.toJSON(v);
                });
            }
        }
        return obj;
    },
    create(base) {
        return SimpleLobbyInfo.fromPartial(base ?? {});
    },
    fromPartial(object) {
        const message = createBaseSimpleLobbyInfo();
        message.partyId = object.partyId ?? "";
        message.memberMap = Object.entries(object.memberMap ?? {}).reduce((acc, [key, value]) => {
            if (value !== undefined) {
                acc[globalThis.Number(key)] = SimpleLocalMember.fromPartial(value);
            }
            return acc;
        }, {});
        return message;
    },
};
function createBaseSimpleLobbyInfo_MemberMapEntry() {
    return { key: 0, value: undefined };
}
export const SimpleLobbyInfo_MemberMapEntry = {
    encode(message, writer = new BinaryWriter()) {
        if (message.key !== 0) {
            writer.uint32(8).int64(message.key);
        }
        if (message.value !== undefined) {
            SimpleLocalMember.encode(message.value, writer.uint32(18).fork()).join();
        }
        return writer;
    },
    decode(input, length) {
        const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
        let end = length === undefined ? reader.len : reader.pos + length;
        const message = createBaseSimpleLobbyInfo_MemberMapEntry();
        while (reader.pos < end) {
            const tag = reader.uint32();
            switch (tag >>> 3) {
                case 1:
                    if (tag !== 8) {
                        break;
                    }
                    message.key = longToNumber(reader.int64());
                    continue;
                case 2:
                    if (tag !== 18) {
                        break;
                    }
                    message.value = SimpleLocalMember.decode(reader, reader.uint32());
                    continue;
            }
            if ((tag & 7) === 4 || tag === 0) {
                break;
            }
            reader.skip(tag & 7);
        }
        return message;
    },
    fromJSON(object) {
        return {
            key: isSet(object.key) ? globalThis.Number(object.key) : 0,
            value: isSet(object.value) ? SimpleLocalMember.fromJSON(object.value) : undefined,
        };
    },
    toJSON(message) {
        const obj = {};
        if (message.key !== 0) {
            obj.key = Math.round(message.key);
        }
        if (message.value !== undefined) {
            obj.value = SimpleLocalMember.toJSON(message.value);
        }
        return obj;
    },
    create(base) {
        return SimpleLobbyInfo_MemberMapEntry.fromPartial(base ?? {});
    },
    fromPartial(object) {
        const message = createBaseSimpleLobbyInfo_MemberMapEntry();
        message.key = object.key ?? 0;
        message.value = (object.value !== undefined && object.value !== null)
            ? SimpleLocalMember.fromPartial(object.value)
            : undefined;
        return message;
    },
};
export const LobbySharingServiceName = "lcu.lobby.LobbySharing";
export class LobbySharingClientImpl {
    rpc;
    service;
    constructor(rpc, opts) {
        this.service = opts?.service || LobbySharingServiceName;
        this.rpc = rpc;
    }
}
function longToNumber(int64) {
    const num = globalThis.Number(int64.toString());
    if (num > globalThis.Number.MAX_SAFE_INTEGER) {
        throw new globalThis.Error("Value is larger than Number.MAX_SAFE_INTEGER");
    }
    if (num < globalThis.Number.MIN_SAFE_INTEGER) {
        throw new globalThis.Error("Value is smaller than Number.MIN_SAFE_INTEGER");
    }
    return num;
}
function isObject(value) {
    return typeof value === "object" && value !== null;
}
function isSet(value) {
    return value !== null && value !== undefined;
}
