syntax = "proto3";

package lcu;

import "common/header.proto";

enum GameflowPhaseEnum {
  Matchmaking = 0; // 正在匹配
  ChampSelect = 1; // 英雄选择中
  ReadyCheck = 2; // 等待接受状态中
  InProgress = 3; // 游戏进行中
  EndOfGame = 4; // 游戏结算
  Lobby = 5; // 房间
  GameStart = 6; //游戏开始
  None = 7; // 无
  Reconnect = 8; // 重新连接
  WaitingForStats = 9; // 等待结果
  PreEndOfGame = 10; // 结束游戏之前
  WatchInProgress = 11; // 在观战中
}

message PhaseWithSummonerId {
  GameflowPhaseEnum phase = 1;
  uint64 summonerId = 2;
}

message GameflowPhaseMessage {
  header.MessageHeader header = 1;
  PhaseWithSummonerId body = 2;
}
