// This file is automatically generated, please do not modify it.


export interface AccountDto {
  puuid: string,

  // This field may be excluded from the response if the account doesn't have a gameName.
  gameName?: string,

  // This field may be excluded from the response if the account doesn't have a tagLine.
  tagLine?: string,
}

export interface ActiveShardDto {
  puuid: string,
  game: string,
  activeShard: string,
}