// This file is automatically generated, please do not modify it.


export interface ChampionInfo {
  maxNewPlayerLevel: number,
  freeChampionIdsForNewPlayers: number[],
  freeChampionIds: number[],
}