// This file is automatically generated, please do not modify it.


export interface PlayerDto {
  summonerId: string,
  teamId?: string,

  // (Legal values:  UNSELECTED,  FILL,  TOP,  JUNGLE,  MIDDLE,  BOTTOM,  UTILITY)
  position: ('UNSELECTED' | 'FILL' | 'TOP' | 'JUNGLE' | 'MIDDLE' | 'BOTTOM' | 'UTILITY'),

  // (Legal values:  CAPTAIN,  MEMBER)
  role: ('CAPTAIN' | 'MEMBER'),
}

export interface TeamDto {
  id: string,
  tournamentId: number,
  name: string,
  iconId: number,
  tier: number,

  // Summoner ID of the team captain.
  captain: string,
  abbreviation: string,

  // Team members.
  players: PlayerDto[],
}

export interface TournamentDto {
  id: number,
  themeId: number,
  nameKey: string,
  nameKeySecondary: string,

  // Tournament phase.
  schedule: TournamentPhaseDto[],
}

export interface TournamentPhaseDto {
  id: number,
  registrationTime: number,
  startTime: number,
  cancelled: boolean,
}
