// This file is automatically generated, please do not modify it.


export interface LeagueListDTO {
  leagueId?: string,
  entries: LeagueItemDTO[],
  tier: string,
  name?: string,
  queue?: string,
}

export interface LeagueItemDTO {
  freshBlood: boolean,

  // Winning team on Summoners Rift.
  wins: number,
  miniSeries?: MiniSeriesDTO,
  inactive: boolean,
  veteran: boolean,
  hotStreak: boolean,
  rank: string,
  leaguePoints: number,

  // Losing team on Summoners Rift.
  losses: number,

  // Player's encrypted summonerId.
  summonerId: string,
}

export interface MiniSeriesDTO {
  losses: number,
  progress: string,
  target: number,
  wins: number,
}

export interface LeagueEntryDTO {
  leagueId?: string,

  // Player's encrypted summonerId.
  summonerId: string,
  queueType: string,
  tier?: string,

  // The player's division within a tier.
  rank?: string,
  leaguePoints: number,

  // Winning team on Summoners Rift.
  wins: number,

  // Losing team on Summoners Rift.
  losses: number,
  hotStreak: boolean,
  veteran: boolean,
  freshBlood: boolean,
  inactive: boolean,
  miniSeries?: MiniSeriesDTO,
}