// This file is automatically generated, please do not modify it.


export interface LeagueEntryDTO {
  leagueId: string,

  // Player's summonerId (Encrypted)
  summonerId: string,
  queueType: string,
  tier: string,

  // The player's division within a tier.
  rank: string,
  leaguePoints: number,

  // Winning team on Summoners Rift. First placement in Teamfight Tactics.
  wins: number,

  // Losing team on Summoners Rift. Second through eighth placement in Teamfight Tactics.
  losses: number,
  hotStreak: boolean,
  veteran: boolean,
  freshBlood: boolean,
  inactive: boolean,
  miniSeries?: MiniSeriesDTO,
}

export interface MiniSeriesDTO {
  losses: number,
  progress: string,
  target: number,
  wins: number,
}