// This file is automatically generated, please do not modify it.


export interface ChallengeConfigInfoDto {
  id: number,
  localizedNames: any,

  // DISABLED - not visible and not calculated, HIDDEN - not visible, but calculated, ENABLED - visible and calculated, ARCHIVED - visible, but not calculated
  state: ('DISABLED' | 'HIDDEN' | 'ENABLED' | 'ARCHIVED'),

  // LIFETIME - stats are incremented without reset, SEASON - stats are accumulated by season and reset at the beginning of new season
  tracking?: ('LIFETIME' | 'SEASON'),
  startTimestamp?: number,
  endTimestamp?: number,
  leaderboard: boolean,
  thresholds: any,
}


// DISABLED - not visible and not calculated,
// HIDDEN - not visible, but calculated,
// ENABLED - visible and calculated,
// ARCHIVED - visible, but not calculated
export interface State {

}


// LIFETIME - stats are incremented without reset,
// SEASON - stats are accumulated by season and reset at the beginning of new season
export interface Tracking {

}

export interface ApexPlayerInfoDto {
  puuid: string,
  value: unknown,
  position: number,
}


// 0 NONE,
// 1 IRON,
// 2 BRONZE,
// 3 SILVER,
// 4 GOLD,
// 5 PLATINUM,
// 6 DIAMOND,
// 7 MASTER,
// 8 GRANDMASTER,
// 9 CHALLENGER
export interface Level {

}

export interface PlayerInfoDto {
  challenges: ChallengeInfo[],
  preferences: PlayerClientPreferences,
  totalPoints: ChallengePoints,
  categoryPoints: any,
}

export interface ChallengeInfo {
  challengeId: number,
  percentile: unknown,
  level: string,
  value: unknown,
  achievedTime?: number,
  position?: number,
  playersInLevel?: number,
}

export interface PlayerClientPreferences {
  bannerAccent?: string,
  title?: string,
  challengeIds?: number[],
  crestBorder?: string,
  prestigeCrestBorderLevel?: number,
}

export interface ChallengePoints {
  level: string,
  current: number,
  max: number,
  percentile?: unknown,
}
