// This file is automatically generated, please do not modify it.


export interface PlatformDataDto {
  id: string,
  name: string,
  locales: string[],
  maintenances: StatusDto[],
  incidents: StatusDto[],
}

export interface StatusDto {
  id: number,

  // (Legal values:  scheduled,  in_progress,  complete)
  maintenance_status: ('scheduled' | 'in_progress' | 'complete'),

  // (Legal values:  info,  warning,  critical)
  incident_severity: ('info' | 'warning' | 'critical'),
  titles: ContentDto[],
  updates: UpdateDto[],
  created_at: string,
  archive_at: string,
  updated_at: string,

  // (Legal values: windows, macos, android, ios, ps4, xbone, switch)
  platforms: ('windows' | 'macos' | 'android' | 'ios' | 'ps4' | 'xbone' | 'switch')[],
}

export interface ContentDto {
  locale: string,
  content: string,
}

export interface UpdateDto {
  id: number,
  author: string,
  publish: boolean,

  // (Legal values: riotclient, riotstatus, game)
  publish_locations: ('riotclient' | 'riotstatus' | 'game')[],
  translations: ContentDto[],
  created_at: string,
  updated_at: string,
}
