// This file is automatically generated, please do not modify it.


export interface LeaderboardDto {

  // A list of players in Master tier.
  players: PlayerDto[],
}

export interface PlayerDto {
  name: string,
  rank: number,

  // League points.
  lp: number,
}