// This file is automatically generated, please do not modify it.


export interface MatchDto {

  // Match metadata.
  metadata: MetadataDto,

  // Match info.
  info: InfoDto,
}

export interface MetadataDto {

  // Match data version.
  data_version: string,

  // Match id.
  match_id: string,

  // A list of participant PUUIDs.
  participants: string[],
}

export interface InfoDto {

  // (Legal values:  Constructed,  Expeditions,  Tutorial)
  game_mode: ('Constructed' | 'Expeditions' | 'Tutorial'),

  // (Legal values:  Ranked,  Normal,  AI,  Tutorial,  VanillaTrial,  Singleton,  StandardGauntlet)
  game_type: ('Ranked' | 'Normal' | 'AI' | 'Tutorial' | 'VanillaTrial' | 'Singleton' | 'StandardGauntlet'),
  game_start_time_utc: string,
  game_version: string,

  // (Legal values:  standard,  eternal)
  game_format: ('standard' | 'eternal'),
  players: PlayerDto[],

  // Total turns taken by both players.
  total_turn_count: number,
}

export interface PlayerDto {
  puuid: string,
  deck_id: string,

  // Code for the deck played. Refer to LOR documentation for details on deck codes.
  deck_code: string,
  factions: string[],
  game_outcome: string,

  // The order in which the players took turns.
  order_of_play: number,
}
