// This file is automatically generated, please do not modify it.


export interface DeckDto {
  id: string,
  name: string,
  code: string,
}

export interface NewDeckDto {
  name: string,
  code: string,
}