// This file is automatically generated, please do not modify it.


export interface CurrentGameInfo {

  // The ID of the game
  gameId: number,

  // The game type
  gameType: string,

  // The game start time represented in epoch milliseconds
  gameStartTime: number,

  // The ID of the map
  mapId: number,

  // The amount of time in seconds that has passed since the game started
  gameLength: number,

  // The ID of the platform on which the game is being played
  platformId: string,

  // The game mode
  gameMode: string,

  // Banned champion information
  bannedChampions: BannedChampion[],

  // The queue type (queue types are documented on the Game Constants page)
  gameQueueConfigId?: number,

  // The observer information
  observers: Observer,

  // The participant information
  participants: CurrentGameParticipant[],
}

export interface BannedChampion {

  // The turn during which the champion was banned
  pickTurn: number,

  // The ID of the banned champion
  championId: number,

  // The ID of the team that banned the champion
  teamId: number,
}

export interface Observer {

  // Key used to decrypt the spectator grid game data for playback
  encryptionKey: string,
}

export interface CurrentGameParticipant {

  // The ID of the champion played by this participant
  championId: number,

  // Perks/Runes Reforged Information
  perks?: Perks,

  // The ID of the profile icon used by this participant
  profileIconId: number,

  // Flag indicating whether not this participant is a bot
  bot: boolean,

  // The team ID of this participant, indicating the participant's team
  teamId: number,

  // The encrypted summoner ID of this participant
  summonerId: string,

  // The encrypted puuid of this participant
  puuid?: string,

  // The ID of the first summoner spell used by this participant
  spell1Id: number,

  // The ID of the second summoner spell used by this participant
  spell2Id: number,

  // List of Game Customizations
  gameCustomizationObjects: GameCustomizationObject[],
  riotId?: string,
}

export interface Perks {

  // IDs of the perks/runes assigned.
  perkIds: number[],

  // Primary runes path
  perkStyle: number,

  // Secondary runes path
  perkSubStyle: number,
}

export interface GameCustomizationObject {

  // Category identifier for Game Customization
  category: string,

  // Game Customization content
  content: string,
}

export interface FeaturedGames {

  // The list of featured games
  gameList: FeaturedGameInfo[],

  // The suggested interval to wait before requesting FeaturedGames again
  clientRefreshInterval?: number,
}

export interface FeaturedGameInfo {

  // The game mode
  //              (Legal values:  CLASSIC,  ODIN,  ARAM,  TUTORIAL,  ONEFORALL,  ASCENSION,  FIRSTBLOOD,  KINGPORO)
  gameMode: ('CLASSIC' | 'ODIN' | 'ARAM' | 'TUTORIAL' | 'ONEFORALL' | 'ASCENSION' | 'FIRSTBLOOD' | 'KINGPORO'),

  // The amount of time in seconds that has passed since the game started
  gameLength: number,

  // The ID of the map
  mapId: number,

  // The game type
  //              (Legal values:  CUSTOM_GAME,  MATCHED_GAME,  TUTORIAL_GAME)
  gameType: ('CUSTOM_GAME' | 'MATCHED_GAME' | 'TUTORIAL_GAME'),

  // Banned champion information
  bannedChampions: BannedChampion[],

  // The ID of the game
  gameId: number,

  // The observer information
  observers: Observer,

  // The queue type (queue types are documented on the Game Constants page)
  gameQueueConfigId: number,

  // The participant information
  participants: Participant[],

  // The ID of the platform on which the game is being played
  platformId: string,
}

export interface Participant {

  // Flag indicating whether not this participant is a bot
  bot: boolean,

  // The ID of the second summoner spell used by this participant
  spell2Id: number,

  // The ID of the profile icon used by this participant
  profileIconId: number,

  // Encrypted summoner ID of this participant
  summonerId?: string,

  // Encrypted puuid of this participant
  puuid?: string,

  // The ID of the champion played by this participant
  championId: number,

  // The team ID of this participant, indicating the participant's team
  teamId: number,

  // The ID of the first summoner spell used by this participant
  spell1Id: number,
  riotId?: string,
}
