// This file is automatically generated, please do not modify it.


export interface LeagueListDTO {
  leagueId?: string,
  entries: LeagueItemDTO[],
  tier: string,
  name?: string,
  queue?: string,
}

export interface LeagueItemDTO {
  freshBlood: boolean,

  // First placement.
  wins: number,
  miniSeries?: MiniSeriesDTO,
  inactive: boolean,
  veteran: boolean,
  hotStreak: boolean,
  rank: string,
  leaguePoints: number,

  // Second through eighth placement.
  losses: number,

  // Player's encrypted summonerId.
  summonerId: string,
}

export interface MiniSeriesDTO {
  losses: number,
  progress: string,
  target: number,
  wins: number,
}

export interface LeagueEntryDTO {

  // Player Universal Unique Identifier. Exact length of 78 characters. (Encrypted)
  puuid?: string,

  // Not included for the RANKED_TFT_TURBO queueType.
  leagueId?: string,

  // Player's encrypted summonerId.
  summonerId: string,
  queueType: string,

  // Only included for the RANKED_TFT_TURBO queueType.
  //              (Legal values:  ORANGE,  PURPLE,  BLUE,  GREEN,  GRAY)
  ratedTier?: ('ORANGE' | 'PURPLE' | 'BLUE' | 'GREEN' | 'GRAY'),

  // Only included for the RANKED_TFT_TURBO queueType.
  ratedRating?: number,

  // Not included for the RANKED_TFT_TURBO queueType.
  tier?: string,

  // The player's division within a tier. Not included for the RANKED_TFT_TURBO queueType.
  rank?: string,

  // Not included for the RANKED_TFT_TURBO queueType.
  leaguePoints?: number,

  // First placement.
  wins: number,

  // Second through eighth placement.
  losses: number,

  // Not included for the RANKED_TFT_TURBO queueType.
  hotStreak?: boolean,

  // Not included for the RANKED_TFT_TURBO queueType.
  veteran?: boolean,

  // Not included for the RANKED_TFT_TURBO queueType.
  freshBlood?: boolean,

  // Not included for the RANKED_TFT_TURBO queueType.
  inactive?: boolean,

  // Not included for the RANKED_TFT_TURBO queueType.
  miniSeries?: MiniSeriesDTO,
}

export interface TopRatedLadderEntryDto {
  summonerId: string,

  // (Legal values:  ORANGE,  PURPLE,  BLUE,  GREEN,  GRAY)
  ratedTier: ('ORANGE' | 'PURPLE' | 'BLUE' | 'GREEN' | 'GRAY'),
  ratedRating: number,

  // First placement.
  wins: number,
  previousUpdateLadderPosition: number,
}
