// This file is automatically generated, please do not modify it.


export interface MatchDto {

  // Match metadata.
  metadata: MetadataDto,

  // Match info.
  info: InfoDto,
}

export interface MetadataDto {

  // Match data version.
  data_version: string,

  // Match id.
  match_id: string,

  // A list of participant PUUIDs.
  participants: string[],
}

export interface InfoDto {

  // Unix timestamp.
  game_datetime: number,

  // Game length in seconds.
  game_length: unknown,

  // Game variation key. Game variations documented in TFT static data.
  game_variation?: string,

  // Game client version.
  game_version: string,
  participants: ParticipantDto[],

  // Please refer to the League of Legends documentation.
  queue_id: number,

  // Teamfight Tactics set number.
  tft_set_number: number,
  tft_game_type?: string,
  tft_set_core_name?: string,
  endOfGameResult?: string,
  gameCreation?: number,
  gameId?: number,
  mapId?: number,

  // Please refer to the League of Legends documentation.
  queueId?: number,
}

export interface ParticipantDto {

  // Participant's companion.
  companion: CompanionDto,

  // Gold left after participant was eliminated.
  gold_left: number,

  // The round the participant was eliminated in. Note: If the player was eliminated in stage 2-1 their last_round would be 5.
  last_round: number,

  // Participant Little Legend level. Note: This is not the number of active units.
  level: number,

  // Participant placement upon elimination.
  placement: number,

  // Number of players the participant eliminated.
  players_eliminated: number,
  puuid: string,

  // The number of seconds before the participant was eliminated.
  time_eliminated: unknown,

  // Damage the participant dealt to other players.
  total_damage_to_players: number,

  // A complete list of traits for the participant's active units.
  traits: TraitDto[],

  // A list of active units for the participant.
  units: UnitDto[],
  augments?: string[],
  partner_group_id?: number,
  missions?: ParticipantMissionsDto,
}

export interface TraitDto {

  // Trait name.
  name: string,

  // Number of units with this trait.
  num_units: number,

  // Current style for this trait. (0 = No style, 1 = Bronze, 2 = Silver, 3 = Gold, 4 = Chromatic)
  style?: number,

  // Current active tier for the trait.
  tier_current: number,

  // Total tiers for the trait.
  tier_total?: number,
}

export interface UnitDto {

  // A list of the unit's items. Please refer to the Teamfight Tactics documentation for item ids.
  items?: number[],

  // This field was introduced in patch 9.22 with data_version 2.
  character_id: string,

  // If a unit is chosen as part of the Fates set mechanic, the chosen trait will be indicated by this field. Otherwise this field is excluded from the response.
  chosen?: string,

  // Unit name. This field is often left blank.
  name: string,

  // Unit rarity. This doesn't equate to the unit cost.
  rarity: number,

  // Unit tier.
  tier: number,
  itemNames?: string[],
}

export interface CompanionDto {
  item_ID?: number,
  skin_ID: number,
  content_ID: string,
  species: string,
}

export interface ParticipantMissionsDto {
  Assists?: number,
  DamageDealt?: number,
  DamageDealtToObjectives?: number,
  DamageDealtToTurrets?: number,
  DamageTaken?: number,
  DoubleKills?: number,
  GoldEarned?: number,
  GoldSpent?: number,
  InhibitorsDestroyed?: number,
  Kills?: number,
  LargestKillingSpree?: number,
  LargestMultiKill?: number,
  MagicDamageDealt?: number,
  MagicDamageDealtToChampions?: number,
  NeutralMinionsKilledTeamJungle?: number,
  PhysicalDamageDealt?: number,
  PhysicalDamageTaken?: number,
  PlayerScore0?: number,
  PlayerScore1?: number,
  PlayerScore2?: number,
  PlayerScore3?: number,
  PlayerScore4?: number,
  PlayerScore5?: number,
  PlayerScore6?: number,
  PlayerScore9?: number,
  PlayerScore10?: number,
  PlayerScore11?: number,
  QuadraKills?: number,
  Spell1Casts?: number,
  Spell2Casts?: number,
  Spell3Casts?: number,
  Spell4Casts?: number,
  SummonerSpell1Casts?: number,
  TimeCCOthers?: number,
  TotalMinionsKilled?: number,
  TrueDamageDealtToChampions?: number,
  UnrealKills?: number,
  VisionScore?: number,
  WardsKilled?: number,
  Deaths?: number,
  KillingSprees?: number,
  MagicDamageTaken?: number,
  PentaKills?: number,
  PhysicalDamageDealtToChampions?: number,
  TotalDamageDealtToChampions?: number,
  TripleKills?: number,
  TrueDamageDealt?: number,
  TrueDamageTaken?: number,
}