// This file is automatically generated, please do not modify it.


export interface TournamentCodeParametersV5 {

  // Optional list of encrypted puuids in order to validate the players eligible to join the lobby. NOTE: We currently do not enforce participants at the team level, but rather the aggregate of teamOne and teamTwo. We may add the ability to enforce at the team level in the future.
  allowedParticipants?: string[],

  // Optional string that may contain any data in any format, if specified at all. Used to denote any custom information about the game.
  metadata?: string,

  // The team size of the game. Valid values are 1-5.
  teamSize: number,

  // The pick type of the game.
  //              (Legal values:  BLIND_PICK,  DRAFT_MODE,  ALL_RANDOM,  TOURNAMENT_DRAFT)
  pickType: ('BLIND_PICK' | 'DRAFT_MODE' | 'ALL_RANDOM' | 'TOURNAMENT_DRAFT'),

  // The map type of the game.
  //              (Legal values:  SUMMONERS_RIFT,  HOWLING_ABYSS)
  mapType: ('SUMMONERS_RIFT' | 'HOWLING_ABYSS'),

  // The spectator type of the game.
  //              (Legal values:  NONE,  LOBBYONLY,  ALL)
  spectatorType: ('NONE' | 'LOBBYONLY' | 'ALL'),

  // Checks if allowed participants are enough to make full teams.
  enoughPlayers: boolean,
}

export interface TournamentCodeV5DTO {

  // The tournament code.
  code: string,

  // The spectator mode for the tournament code game.
  spectators: string,

  // The lobby name for the tournament code game.
  lobbyName: string,

  // The metadata for tournament code.
  metaData: string,

  // The password for the tournament code game.
  password: string,

  // The team size for the tournament code game.
  teamSize: number,

  // The provider's ID.
  providerId: number,

  // The pick mode for tournament code game.
  pickType: string,

  // The tournament's ID.
  tournamentId: number,

  // The tournament code's ID.
  id: number,

  // The tournament code's region.
  //              (Legal values:  BR,  EUNE,  EUW,  JP,  LAN,  LAS,  NA,  OCE,  PBE,  RU,  TR,  KR)
  region: ('BR' | 'EUNE' | 'EUW' | 'JP' | 'LAN' | 'LAS' | 'NA' | 'OCE' | 'PBE' | 'RU' | 'TR' | 'KR'),

  // The game map for the tournament code game
  map: string,

  // The puuids of the participants (Encrypted)
  participants: string[],
}

export interface LobbyEventV5DTOWrapper {
  eventList: LobbyEventV5DTO[],
}

export interface LobbyEventV5DTO {

  // Timestamp from the event
  timestamp: string,

  // The type of event that was triggered
  eventType: string,

  // The puuid that triggered the event (Encrypted)
  puuid: string,
}

export interface ProviderRegistrationParametersV5 {

  // The region in which the provider will be running tournaments.
  //              (Legal values:  BR,  EUNE,  EUW,  JP,  LAN,  LAS,  NA,  OCE,  PBE,  RU,  TR,  KR)
  region: ('BR' | 'EUNE' | 'EUW' | 'JP' | 'LAN' | 'LAS' | 'NA' | 'OCE' | 'PBE' | 'RU' | 'TR' | 'KR'),

  // The provider's callback URL to which tournament game results in this region should be posted. The URL must be well-formed, use the http or https protocol, and use the default port for the protocol (http URLs must use port 80, https URLs must use port 443).
  url: string,
}

export interface TournamentRegistrationParametersV5 {

  // The provider ID to specify the regional registered provider data to associate this tournament.
  providerId: number,

  // The optional name of the tournament.
  name?: string,
}
