// This file is automatically generated, please do not modify it.


export interface MatchDto {
  matchInfo: MatchInfoDto,
  players: PlayerDto[],
  coaches: CoachDto[],
  teams: TeamDto[],
  roundResults: RoundResultDto[],
}

export interface MatchInfoDto {
  matchId: string,
  mapId: string,
  gameLengthMillis: number,
  gameStartMillis: number,
  provisioningFlowId: string,
  isCompleted: boolean,
  customGameName: string,
  queueId: string,
  gameMode: string,
  isRanked: boolean,
  seasonId: string,
}

export interface PlayerDto {
  puuid: string,
  gameName: string,
  tagLine: string,
  teamId: string,
  partyId: string,
  characterId: string,
  stats: PlayerStatsDto,
  competitiveTier: number,
  playerCard: string,
  playerTitle: string,
}

export interface PlayerStatsDto {
  score: number,
  roundsPlayed: number,
  kills: number,
  deaths: number,
  assists: number,
  playtimeMillis: number,
  abilityCasts: AbilityCastsDto,
}

export interface AbilityCastsDto {
  grenadeCasts: number,
  ability1Casts: number,
  ability2Casts: number,
  ultimateCasts: number,
}

export interface CoachDto {
  puuid: string,
  teamId: string,
}

export interface TeamDto {

  // This is an arbitrary string. Red and Blue in bomb modes. The puuid of the player in deathmatch.
  teamId: string,
  won: boolean,
  roundsPlayed: number,
  roundsWon: number,

  // Team points scored. Number of kills in deathmatch.
  numPoints: number,
}

export interface RoundResultDto {
  roundNum: number,
  roundResult: string,
  roundCeremony: string,
  winningTeam: string,

  // PUUID of player
  bombPlanter: string,

  // PUUID of player
  bombDefuser: string,
  plantRoundTime: number,
  plantPlayerLocations: PlayerLocationsDto[],
  plantLocation: LocationDto,
  plantSite: string,
  defuseRoundTime: number,
  defusePlayerLocations: PlayerLocationsDto[],
  defuseLocation: LocationDto,
  playerStats: PlayerRoundStatsDto[],
  roundResultCode: string,
}

export interface PlayerLocationsDto {
  puuid: string,
  viewRadians: unknown,
  location: LocationDto,
}

export interface LocationDto {
  x: number,
  y: number,
}

export interface PlayerRoundStatsDto {
  puuid: string,
  kills: KillDto[],
  damage: DamageDto[],
  score: number,
  economy: EconomyDto,
  ability: AbilityDto,
}

export interface KillDto {
  timeSinceGameStartMillis: number,
  timeSinceRoundStartMillis: number,

  // PUUID
  killer: string,

  // PUUID
  victim: string,
  victimLocation: LocationDto,

  // List of PUUIDs
  assistants: string[],
  playerLocations: PlayerLocationsDto[],
  finishingDamage: FinishingDamageDto,
}

export interface FinishingDamageDto {
  damageType: string,
  damageItem: string,
  isSecondaryFireMode: boolean,
}

export interface DamageDto {

  // PUUID
  receiver: string,
  damage: number,
  legshots: number,
  bodyshots: number,
  headshots: number,
}

export interface EconomyDto {
  loadoutValue: number,
  weapon: string,
  armor: string,
  remaining: number,
  spent: number,
}

export interface AbilityDto {
  grenadeEffects: string,
  ability1Effects: string,
  ability2Effects: string,
  ultimateEffects: string,
}

export interface MatchlistDto {
  puuid: string,
  history: MatchlistEntryDto[],
}

export interface MatchlistEntryDto {
  matchId: string,
  gameStartTimeMillis: number,
  queueId: string,
}

export interface RecentMatchesDto {
  currentTime: number,

  // A list of recent match ids.
  matchIds: string[],
}