// This file is automatically generated, please do not modify it.


export interface LeaderboardDto {

  // The shard for the given leaderboard.
  shard: string,

  // The act id for the given leaderboard. Act ids can be found using the val-content API.
  actId: string,

  // The total number of players in the leaderboard.
  totalPlayers: number,
  players: PlayerDto[],
  immortalStartingPage?: number,
  immortalStartingIndex?: number,
  topTierRRThreshold?: number,
  tierDetails?: any,
  startIndex?: number,
  query?: string,
}

export interface PlayerDto {

  // This field may be omitted if the player has been anonymized.
  puuid?: string,

  // This field may be omitted if the player has been anonymized.
  gameName?: string,

  // This field may be omitted if the player has been anonymized.
  tagLine?: string,
  leaderboardRank: number,
  rankedRating: number,
  numberOfWins: number,
  competitiveTier?: number,
}

export interface TierDetailDto {
  rankedRatingThreshold: number,
  startingPage: number,
  startingIndex: number,
}