// This file is automatically generated, please do not modify it.


export interface ContentDto {
  version: string,
  characters: ContentItemDto[],
  maps: ContentItemDto[],
  chromas: ContentItemDto[],
  skins: ContentItemDto[],
  skinLevels: ContentItemDto[],
  equips: ContentItemDto[],
  gameModes: ContentItemDto[],
  sprays: ContentItemDto[],
  sprayLevels: ContentItemDto[],
  charms: ContentItemDto[],
  charmLevels: ContentItemDto[],
  playerCards: ContentItemDto[],
  playerTitles: ContentItemDto[],
  acts: ActDto[],
  ceremonies?: ContentItemDto[],

  // Unknown type, this is a placeholder subject to change.
  totems?: string[],
}

export interface ContentItemDto {
  name: string,

  // This field is excluded from the response when a locale is set
  localizedNames?: LocalizedNamesDto,
  id: string,
  assetName: string,

  // This field is only included for maps and game modes. These values are used in the match response.
  assetPath?: string,
}

export interface LocalizedNamesDto {
  ar-AE: string,
  de-DE: string,
  en-GB?: string,
  en-US: string,
  es-ES: string,
  es-MX: string,
  fr-FR: string,
  id-ID: string,
  it-IT: string,
  ja-JP: string,
  ko-KR: string,
  pl-PL: string,
  pt-BR: string,
  ru-RU: string,
  th-TH: string,
  tr-TR: string,
  vi-VN: string,
  zh-CN: string,
  zh-TW: string,
}

export interface ActDto {
  name: string,

  // This field is excluded from the response when a locale is set
  localizedNames?: LocalizedNamesDto,
  id: string,
  isActive: boolean,
  parentId?: string,
  type?: string,
}