// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.0.2
//   protoc               v5.27.3
// source: lcu/gameflow.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";

export enum GameflowPhaseEnum {
  /** Matchmaking - 正在匹配 */
  Matchmaking = 0,
  /** ChampSelect - 英雄选择中 */
  ChampSelect = 1,
  /** ReadyCheck - 等待接受状态中 */
  ReadyCheck = 2,
  /** InProgress - 游戏进行中 */
  InProgress = 3,
  /** EndOfGame - 游戏结算 */
  EndOfGame = 4,
  /** Lobby - 房间 */
  Lobby = 5,
  /** GameStart - 游戏开始 */
  GameStart = 6,
  /** None - 无 */
  None = 7,
  /** Reconnect - 重新连接 */
  Reconnect = 8,
  /** WaitingForStats - 等待结果 */
  WaitingForStats = 9,
  /** PreEndOfGame - 结束游戏之前 */
  PreEndOfGame = 10,
  /** WatchInProgress - 在观战中 */
  WatchInProgress = 11,
  UNRECOGNIZED = -1,
}

export function gameflowPhaseEnumFromJSON(object: any): GameflowPhaseEnum {
  switch (object) {
    case 0:
    case "Matchmaking":
      return GameflowPhaseEnum.Matchmaking;
    case 1:
    case "ChampSelect":
      return GameflowPhaseEnum.ChampSelect;
    case 2:
    case "ReadyCheck":
      return GameflowPhaseEnum.ReadyCheck;
    case 3:
    case "InProgress":
      return GameflowPhaseEnum.InProgress;
    case 4:
    case "EndOfGame":
      return GameflowPhaseEnum.EndOfGame;
    case 5:
    case "Lobby":
      return GameflowPhaseEnum.Lobby;
    case 6:
    case "GameStart":
      return GameflowPhaseEnum.GameStart;
    case 7:
    case "None":
      return GameflowPhaseEnum.None;
    case 8:
    case "Reconnect":
      return GameflowPhaseEnum.Reconnect;
    case 9:
    case "WaitingForStats":
      return GameflowPhaseEnum.WaitingForStats;
    case 10:
    case "PreEndOfGame":
      return GameflowPhaseEnum.PreEndOfGame;
    case 11:
    case "WatchInProgress":
      return GameflowPhaseEnum.WatchInProgress;
    case -1:
    case "UNRECOGNIZED":
    default:
      return GameflowPhaseEnum.UNRECOGNIZED;
  }
}

export function gameflowPhaseEnumToJSON(object: GameflowPhaseEnum): string {
  switch (object) {
    case GameflowPhaseEnum.Matchmaking:
      return "Matchmaking";
    case GameflowPhaseEnum.ChampSelect:
      return "ChampSelect";
    case GameflowPhaseEnum.ReadyCheck:
      return "ReadyCheck";
    case GameflowPhaseEnum.InProgress:
      return "InProgress";
    case GameflowPhaseEnum.EndOfGame:
      return "EndOfGame";
    case GameflowPhaseEnum.Lobby:
      return "Lobby";
    case GameflowPhaseEnum.GameStart:
      return "GameStart";
    case GameflowPhaseEnum.None:
      return "None";
    case GameflowPhaseEnum.Reconnect:
      return "Reconnect";
    case GameflowPhaseEnum.WaitingForStats:
      return "WaitingForStats";
    case GameflowPhaseEnum.PreEndOfGame:
      return "PreEndOfGame";
    case GameflowPhaseEnum.WatchInProgress:
      return "WatchInProgress";
    case GameflowPhaseEnum.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

export interface PhaseWithSummonerId {
  phase: GameflowPhaseEnum;
  summonerId: number;
}

function createBasePhaseWithSummonerId(): PhaseWithSummonerId {
  return { phase: 0, summonerId: 0 };
}

export const PhaseWithSummonerId = {
  encode(message: PhaseWithSummonerId, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.phase !== 0) {
      writer.uint32(8).int32(message.phase);
    }
    if (message.summonerId !== 0) {
      writer.uint32(16).uint64(message.summonerId);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): PhaseWithSummonerId {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBasePhaseWithSummonerId();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 8) {
            break;
          }

          message.phase = reader.int32() as any;
          continue;
        case 2:
          if (tag !== 16) {
            break;
          }

          message.summonerId = longToNumber(reader.uint64());
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): PhaseWithSummonerId {
    return {
      phase: isSet(object.phase) ? gameflowPhaseEnumFromJSON(object.phase) : 0,
      summonerId: isSet(object.summonerId) ? globalThis.Number(object.summonerId) : 0,
    };
  },

  toJSON(message: PhaseWithSummonerId): unknown {
    const obj: any = {};
    if (message.phase !== 0) {
      obj.phase = gameflowPhaseEnumToJSON(message.phase);
    }
    if (message.summonerId !== 0) {
      obj.summonerId = Math.round(message.summonerId);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<PhaseWithSummonerId>, I>>(base?: I): PhaseWithSummonerId {
    return PhaseWithSummonerId.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<PhaseWithSummonerId>, I>>(object: I): PhaseWithSummonerId {
    const message = createBasePhaseWithSummonerId();
    message.phase = object.phase ?? 0;
    message.summonerId = object.summonerId ?? 0;
    return message;
  },
};

export interface GamePhaseSharing {
}

export const GamePhaseSharingServiceName = "lcu.gameflow.GamePhaseSharing";
export class GamePhaseSharingClientImpl implements GamePhaseSharing {
  private readonly rpc: Rpc;
  private readonly service: string;
  constructor(rpc: Rpc, opts?: { service?: string }) {
    this.service = opts?.service || GamePhaseSharingServiceName;
    this.rpc = rpc;
  }
}

interface Rpc {
  request(service: string, method: string, data: Uint8Array): Promise<Uint8Array>;
}

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function longToNumber(int64: { toString(): string }): number {
  const num = globalThis.Number(int64.toString());
  if (num > globalThis.Number.MAX_SAFE_INTEGER) {
    throw new globalThis.Error("Value is larger than Number.MAX_SAFE_INTEGER");
  }
  if (num < globalThis.Number.MIN_SAFE_INTEGER) {
    throw new globalThis.Error("Value is smaller than Number.MIN_SAFE_INTEGER");
  }
  return num;
}

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}
