// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.0.2
//   protoc               v5.27.3
// source: lcu/summoner.proto
/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
function createBaseRerollPoints() {
    return { currentPoints: 0, maxRolls: 0, numberOfRolls: 0, pointsCostToRoll: 0, pointsToReroll: 0 };
}
export const RerollPoints = {
    encode(message, writer = new BinaryWriter()) {
        if (message.currentPoints !== 0) {
            writer.uint32(8).int32(message.currentPoints);
        }
        if (message.maxRolls !== 0) {
            writer.uint32(16).int32(message.maxRolls);
        }
        if (message.numberOfRolls !== 0) {
            writer.uint32(24).int32(message.numberOfRolls);
        }
        if (message.pointsCostToRoll !== 0) {
            writer.uint32(32).int32(message.pointsCostToRoll);
        }
        if (message.pointsToReroll !== 0) {
            writer.uint32(40).int32(message.pointsToReroll);
        }
        return writer;
    },
    decode(input, length) {
        const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
        let end = length === undefined ? reader.len : reader.pos + length;
        const message = createBaseRerollPoints();
        while (reader.pos < end) {
            const tag = reader.uint32();
            switch (tag >>> 3) {
                case 1:
                    if (tag !== 8) {
                        break;
                    }
                    message.currentPoints = reader.int32();
                    continue;
                case 2:
                    if (tag !== 16) {
                        break;
                    }
                    message.maxRolls = reader.int32();
                    continue;
                case 3:
                    if (tag !== 24) {
                        break;
                    }
                    message.numberOfRolls = reader.int32();
                    continue;
                case 4:
                    if (tag !== 32) {
                        break;
                    }
                    message.pointsCostToRoll = reader.int32();
                    continue;
                case 5:
                    if (tag !== 40) {
                        break;
                    }
                    message.pointsToReroll = reader.int32();
                    continue;
            }
            if ((tag & 7) === 4 || tag === 0) {
                break;
            }
            reader.skip(tag & 7);
        }
        return message;
    },
    fromJSON(object) {
        return {
            currentPoints: isSet(object.currentPoints) ? globalThis.Number(object.currentPoints) : 0,
            maxRolls: isSet(object.maxRolls) ? globalThis.Number(object.maxRolls) : 0,
            numberOfRolls: isSet(object.numberOfRolls) ? globalThis.Number(object.numberOfRolls) : 0,
            pointsCostToRoll: isSet(object.pointsCostToRoll) ? globalThis.Number(object.pointsCostToRoll) : 0,
            pointsToReroll: isSet(object.pointsToReroll) ? globalThis.Number(object.pointsToReroll) : 0,
        };
    },
    toJSON(message) {
        const obj = {};
        if (message.currentPoints !== 0) {
            obj.currentPoints = Math.round(message.currentPoints);
        }
        if (message.maxRolls !== 0) {
            obj.maxRolls = Math.round(message.maxRolls);
        }
        if (message.numberOfRolls !== 0) {
            obj.numberOfRolls = Math.round(message.numberOfRolls);
        }
        if (message.pointsCostToRoll !== 0) {
            obj.pointsCostToRoll = Math.round(message.pointsCostToRoll);
        }
        if (message.pointsToReroll !== 0) {
            obj.pointsToReroll = Math.round(message.pointsToReroll);
        }
        return obj;
    },
    create(base) {
        return RerollPoints.fromPartial(base ?? {});
    },
    fromPartial(object) {
        const message = createBaseRerollPoints();
        message.currentPoints = object.currentPoints ?? 0;
        message.maxRolls = object.maxRolls ?? 0;
        message.numberOfRolls = object.numberOfRolls ?? 0;
        message.pointsCostToRoll = object.pointsCostToRoll ?? 0;
        message.pointsToReroll = object.pointsToReroll ?? 0;
        return message;
    },
};
function createBaseSummonerBaseInfo() {
    return {
        unnamed: false,
        nameChangeFlag: false,
        accountId: 0,
        percentCompleteForNextLevel: 0,
        profileIconId: 0,
        summonerId: 0,
        summonerLevel: 0,
        xpSinceLastLevel: 0,
        xpUntilNextLevel: 0,
        displayName: "",
        gameName: "",
        internalName: "",
        privacy: "",
        puuid: "",
        tagLine: "",
    };
}
export const SummonerBaseInfo = {
    encode(message, writer = new BinaryWriter()) {
        if (message.unnamed !== false) {
            writer.uint32(8).bool(message.unnamed);
        }
        if (message.nameChangeFlag !== false) {
            writer.uint32(16).bool(message.nameChangeFlag);
        }
        if (message.accountId !== 0) {
            writer.uint32(24).int64(message.accountId);
        }
        if (message.percentCompleteForNextLevel !== 0) {
            writer.uint32(32).int32(message.percentCompleteForNextLevel);
        }
        if (message.profileIconId !== 0) {
            writer.uint32(40).int32(message.profileIconId);
        }
        if (message.summonerId !== 0) {
            writer.uint32(48).int64(message.summonerId);
        }
        if (message.summonerLevel !== 0) {
            writer.uint32(56).int32(message.summonerLevel);
        }
        if (message.xpSinceLastLevel !== 0) {
            writer.uint32(64).int64(message.xpSinceLastLevel);
        }
        if (message.xpUntilNextLevel !== 0) {
            writer.uint32(72).int64(message.xpUntilNextLevel);
        }
        if (message.displayName !== "") {
            writer.uint32(82).string(message.displayName);
        }
        if (message.gameName !== "") {
            writer.uint32(90).string(message.gameName);
        }
        if (message.internalName !== "") {
            writer.uint32(98).string(message.internalName);
        }
        if (message.privacy !== "") {
            writer.uint32(106).string(message.privacy);
        }
        if (message.puuid !== "") {
            writer.uint32(114).string(message.puuid);
        }
        if (message.tagLine !== "") {
            writer.uint32(122).string(message.tagLine);
        }
        return writer;
    },
    decode(input, length) {
        const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
        let end = length === undefined ? reader.len : reader.pos + length;
        const message = createBaseSummonerBaseInfo();
        while (reader.pos < end) {
            const tag = reader.uint32();
            switch (tag >>> 3) {
                case 1:
                    if (tag !== 8) {
                        break;
                    }
                    message.unnamed = reader.bool();
                    continue;
                case 2:
                    if (tag !== 16) {
                        break;
                    }
                    message.nameChangeFlag = reader.bool();
                    continue;
                case 3:
                    if (tag !== 24) {
                        break;
                    }
                    message.accountId = longToNumber(reader.int64());
                    continue;
                case 4:
                    if (tag !== 32) {
                        break;
                    }
                    message.percentCompleteForNextLevel = reader.int32();
                    continue;
                case 5:
                    if (tag !== 40) {
                        break;
                    }
                    message.profileIconId = reader.int32();
                    continue;
                case 6:
                    if (tag !== 48) {
                        break;
                    }
                    message.summonerId = longToNumber(reader.int64());
                    continue;
                case 7:
                    if (tag !== 56) {
                        break;
                    }
                    message.summonerLevel = reader.int32();
                    continue;
                case 8:
                    if (tag !== 64) {
                        break;
                    }
                    message.xpSinceLastLevel = longToNumber(reader.int64());
                    continue;
                case 9:
                    if (tag !== 72) {
                        break;
                    }
                    message.xpUntilNextLevel = longToNumber(reader.int64());
                    continue;
                case 10:
                    if (tag !== 82) {
                        break;
                    }
                    message.displayName = reader.string();
                    continue;
                case 11:
                    if (tag !== 90) {
                        break;
                    }
                    message.gameName = reader.string();
                    continue;
                case 12:
                    if (tag !== 98) {
                        break;
                    }
                    message.internalName = reader.string();
                    continue;
                case 13:
                    if (tag !== 106) {
                        break;
                    }
                    message.privacy = reader.string();
                    continue;
                case 14:
                    if (tag !== 114) {
                        break;
                    }
                    message.puuid = reader.string();
                    continue;
                case 15:
                    if (tag !== 122) {
                        break;
                    }
                    message.tagLine = reader.string();
                    continue;
            }
            if ((tag & 7) === 4 || tag === 0) {
                break;
            }
            reader.skip(tag & 7);
        }
        return message;
    },
    fromJSON(object) {
        return {
            unnamed: isSet(object.unnamed) ? globalThis.Boolean(object.unnamed) : false,
            nameChangeFlag: isSet(object.nameChangeFlag) ? globalThis.Boolean(object.nameChangeFlag) : false,
            accountId: isSet(object.accountId) ? globalThis.Number(object.accountId) : 0,
            percentCompleteForNextLevel: isSet(object.percentCompleteForNextLevel)
                ? globalThis.Number(object.percentCompleteForNextLevel)
                : 0,
            profileIconId: isSet(object.profileIconId) ? globalThis.Number(object.profileIconId) : 0,
            summonerId: isSet(object.summonerId) ? globalThis.Number(object.summonerId) : 0,
            summonerLevel: isSet(object.summonerLevel) ? globalThis.Number(object.summonerLevel) : 0,
            xpSinceLastLevel: isSet(object.xpSinceLastLevel) ? globalThis.Number(object.xpSinceLastLevel) : 0,
            xpUntilNextLevel: isSet(object.xpUntilNextLevel) ? globalThis.Number(object.xpUntilNextLevel) : 0,
            displayName: isSet(object.displayName) ? globalThis.String(object.displayName) : "",
            gameName: isSet(object.gameName) ? globalThis.String(object.gameName) : "",
            internalName: isSet(object.internalName) ? globalThis.String(object.internalName) : "",
            privacy: isSet(object.privacy) ? globalThis.String(object.privacy) : "",
            puuid: isSet(object.puuid) ? globalThis.String(object.puuid) : "",
            tagLine: isSet(object.tagLine) ? globalThis.String(object.tagLine) : "",
        };
    },
    toJSON(message) {
        const obj = {};
        if (message.unnamed !== false) {
            obj.unnamed = message.unnamed;
        }
        if (message.nameChangeFlag !== false) {
            obj.nameChangeFlag = message.nameChangeFlag;
        }
        if (message.accountId !== 0) {
            obj.accountId = Math.round(message.accountId);
        }
        if (message.percentCompleteForNextLevel !== 0) {
            obj.percentCompleteForNextLevel = Math.round(message.percentCompleteForNextLevel);
        }
        if (message.profileIconId !== 0) {
            obj.profileIconId = Math.round(message.profileIconId);
        }
        if (message.summonerId !== 0) {
            obj.summonerId = Math.round(message.summonerId);
        }
        if (message.summonerLevel !== 0) {
            obj.summonerLevel = Math.round(message.summonerLevel);
        }
        if (message.xpSinceLastLevel !== 0) {
            obj.xpSinceLastLevel = Math.round(message.xpSinceLastLevel);
        }
        if (message.xpUntilNextLevel !== 0) {
            obj.xpUntilNextLevel = Math.round(message.xpUntilNextLevel);
        }
        if (message.displayName !== "") {
            obj.displayName = message.displayName;
        }
        if (message.gameName !== "") {
            obj.gameName = message.gameName;
        }
        if (message.internalName !== "") {
            obj.internalName = message.internalName;
        }
        if (message.privacy !== "") {
            obj.privacy = message.privacy;
        }
        if (message.puuid !== "") {
            obj.puuid = message.puuid;
        }
        if (message.tagLine !== "") {
            obj.tagLine = message.tagLine;
        }
        return obj;
    },
    create(base) {
        return SummonerBaseInfo.fromPartial(base ?? {});
    },
    fromPartial(object) {
        const message = createBaseSummonerBaseInfo();
        message.unnamed = object.unnamed ?? false;
        message.nameChangeFlag = object.nameChangeFlag ?? false;
        message.accountId = object.accountId ?? 0;
        message.percentCompleteForNextLevel = object.percentCompleteForNextLevel ?? 0;
        message.profileIconId = object.profileIconId ?? 0;
        message.summonerId = object.summonerId ?? 0;
        message.summonerLevel = object.summonerLevel ?? 0;
        message.xpSinceLastLevel = object.xpSinceLastLevel ?? 0;
        message.xpUntilNextLevel = object.xpUntilNextLevel ?? 0;
        message.displayName = object.displayName ?? "";
        message.gameName = object.gameName ?? "";
        message.internalName = object.internalName ?? "";
        message.privacy = object.privacy ?? "";
        message.puuid = object.puuid ?? "";
        message.tagLine = object.tagLine ?? "";
        return message;
    },
};
function createBaseSummonerInfoRaw() {
    return { base: undefined, rerollPoints: undefined };
}
export const SummonerInfoRaw = {
    encode(message, writer = new BinaryWriter()) {
        if (message.base !== undefined) {
            SummonerBaseInfo.encode(message.base, writer.uint32(10).fork()).join();
        }
        if (message.rerollPoints !== undefined) {
            RerollPoints.encode(message.rerollPoints, writer.uint32(18).fork()).join();
        }
        return writer;
    },
    decode(input, length) {
        const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
        let end = length === undefined ? reader.len : reader.pos + length;
        const message = createBaseSummonerInfoRaw();
        while (reader.pos < end) {
            const tag = reader.uint32();
            switch (tag >>> 3) {
                case 1:
                    if (tag !== 10) {
                        break;
                    }
                    message.base = SummonerBaseInfo.decode(reader, reader.uint32());
                    continue;
                case 2:
                    if (tag !== 18) {
                        break;
                    }
                    message.rerollPoints = RerollPoints.decode(reader, reader.uint32());
                    continue;
            }
            if ((tag & 7) === 4 || tag === 0) {
                break;
            }
            reader.skip(tag & 7);
        }
        return message;
    },
    fromJSON(object) {
        return {
            base: isSet(object.base) ? SummonerBaseInfo.fromJSON(object.base) : undefined,
            rerollPoints: isSet(object.rerollPoints) ? RerollPoints.fromJSON(object.rerollPoints) : undefined,
        };
    },
    toJSON(message) {
        const obj = {};
        if (message.base !== undefined) {
            obj.base = SummonerBaseInfo.toJSON(message.base);
        }
        if (message.rerollPoints !== undefined) {
            obj.rerollPoints = RerollPoints.toJSON(message.rerollPoints);
        }
        return obj;
    },
    create(base) {
        return SummonerInfoRaw.fromPartial(base ?? {});
    },
    fromPartial(object) {
        const message = createBaseSummonerInfoRaw();
        message.base = (object.base !== undefined && object.base !== null)
            ? SummonerBaseInfo.fromPartial(object.base)
            : undefined;
        message.rerollPoints = (object.rerollPoints !== undefined && object.rerollPoints !== null)
            ? RerollPoints.fromPartial(object.rerollPoints)
            : undefined;
        return message;
    },
};
export const SummonerSharingServiceName = "lcu.summoner.SummonerSharing";
export class SummonerSharingClientImpl {
    rpc;
    service;
    constructor(rpc, opts) {
        this.service = opts?.service || SummonerSharingServiceName;
        this.rpc = rpc;
    }
}
function longToNumber(int64) {
    const num = globalThis.Number(int64.toString());
    if (num > globalThis.Number.MAX_SAFE_INTEGER) {
        throw new globalThis.Error("Value is larger than Number.MAX_SAFE_INTEGER");
    }
    if (num < globalThis.Number.MIN_SAFE_INTEGER) {
        throw new globalThis.Error("Value is smaller than Number.MIN_SAFE_INTEGER");
    }
    return num;
}
function isSet(value) {
    return value !== null && value !== undefined;
}
