// This file is @generated by prost-build.
#[derive(serde::Serialize, serde::Deserialize)]
#[serde(rename_all = "camelCase")]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct MatchHistory {
    #[prost(uint64, tag = "1")]
    pub account_id: u64,
    #[prost(string, tag = "2")]
    pub platform_id: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "3")]
    pub games: ::core::option::Option<Games>,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[serde(rename_all = "camelCase")]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Games {
    #[prost(uint32, tag = "1")]
    pub game_count: u32,
    #[prost(uint32, tag = "2")]
    pub game_index_begin: u32,
    #[prost(uint32, tag = "3")]
    pub game_index_end: u32,
    #[prost(string, tag = "4")]
    pub game_begin_date: ::prost::alloc::string::String,
    #[prost(string, tag = "5")]
    pub game_end_date: ::prost::alloc::string::String,
    #[prost(message, repeated, tag = "6")]
    pub games: ::prost::alloc::vec::Vec<Game>,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[serde(rename_all = "camelCase")]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Game {
    #[prost(uint32, tag = "1")]
    pub game_duration: u32,
    #[prost(uint32, tag = "2")]
    pub map_id: u32,
    #[prost(uint32, tag = "3")]
    pub queue_id: u32,
    #[prost(uint32, tag = "4")]
    pub season_id: u32,
    #[prost(uint64, tag = "5")]
    pub game_id: u64,
    #[prost(uint64, tag = "6")]
    pub game_creation: u64,
    #[prost(string, tag = "7")]
    pub game_creation_date: ::prost::alloc::string::String,
    #[prost(string, tag = "8")]
    pub game_version: ::prost::alloc::string::String,
    #[prost(string, tag = "9")]
    pub game_mode: ::prost::alloc::string::String,
    #[prost(string, tag = "10")]
    pub game_type: ::prost::alloc::string::String,
    #[prost(string, tag = "11")]
    pub platform_id: ::prost::alloc::string::String,
    #[prost(string, tag = "12")]
    pub end_of_game_result: ::prost::alloc::string::String,
    #[prost(message, repeated, tag = "13")]
    pub participant_identities: ::prost::alloc::vec::Vec<ParticipantIdentity>,
    #[prost(message, repeated, tag = "14")]
    pub participants: ::prost::alloc::vec::Vec<Participant>,
    #[prost(message, repeated, tag = "15")]
    pub teams: ::prost::alloc::vec::Vec<Team>,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[serde(rename_all = "camelCase")]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GameExt {
    #[prost(message, optional, tag = "1")]
    pub raw: ::core::option::Option<Game>,
    #[prost(message, repeated, tag = "2")]
    pub id_tuples: ::prost::alloc::vec::Vec<ParticipantIdentityTuple>,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[serde(rename_all = "camelCase")]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Team {
    #[prost(bool, tag = "1")]
    pub first_blood: bool,
    #[prost(bool, tag = "2")]
    pub first_tower: bool,
    #[prost(bool, tag = "3")]
    pub first_inhibitor: bool,
    #[prost(bool, tag = "4")]
    pub first_baron: bool,
    /// Keep typo for consistency
    #[prost(bool, tag = "5")]
    pub first_dargon: bool,
    #[prost(uint32, tag = "6")]
    pub team_id: u32,
    #[prost(uint32, tag = "7")]
    pub tower_kills: u32,
    #[prost(uint32, tag = "8")]
    pub inhibitor_kills: u32,
    #[prost(uint32, tag = "9")]
    pub baron_kills: u32,
    #[prost(uint32, tag = "10")]
    pub dragon_kills: u32,
    #[prost(uint32, tag = "11")]
    pub rift_herald_kills: u32,
    #[prost(uint32, tag = "12")]
    pub vilemaw_kills: u32,
    #[prost(uint32, tag = "13")]
    pub dominion_victory_score: u32,
    /// bytes bans = 15;
    #[prost(string, tag = "14")]
    pub win: ::prost::alloc::string::String,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[serde(rename_all = "camelCase")]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Participant {
    #[prost(uint32, tag = "1")]
    pub participant_id: u32,
    #[prost(uint32, tag = "2")]
    pub team_id: u32,
    #[prost(uint32, tag = "3")]
    pub champion_id: u32,
    #[prost(uint32, tag = "4")]
    pub spell1_id: u32,
    #[prost(uint32, tag = "5")]
    pub spell2_id: u32,
    #[prost(string, tag = "6")]
    pub highest_achieved_season_tier: ::prost::alloc::string::String,
    /// Timeline timeline = 8;
    #[prost(message, optional, tag = "7")]
    pub stats: ::core::option::Option<Stats>,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[serde(rename_all = "camelCase")]
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct Stats {
    #[prost(bool, tag = "1")]
    pub caused_early_surrender: bool,
    #[prost(bool, tag = "2")]
    pub early_surrender_accomplice: bool,
    #[prost(bool, tag = "3")]
    pub first_blood_assist: bool,
    #[prost(bool, tag = "4")]
    pub first_blood_kill: bool,
    #[prost(bool, tag = "5")]
    pub first_inhibitor_assist: bool,
    #[prost(bool, tag = "6")]
    pub first_inhibitor_kill: bool,
    #[prost(bool, tag = "7")]
    pub first_tower_assist: bool,
    #[prost(bool, tag = "8")]
    pub first_tower_kill: bool,
    #[prost(bool, tag = "9")]
    pub game_ended_in_early_surrender: bool,
    #[prost(bool, tag = "10")]
    pub game_ended_in_surrender: bool,
    #[prost(bool, tag = "11")]
    pub team_early_surrendered: bool,
    #[prost(bool, tag = "12")]
    pub win: bool,
    #[prost(uint32, tag = "13")]
    pub assists: u32,
    #[prost(uint32, tag = "14")]
    pub champ_level: u32,
    #[prost(uint32, tag = "15")]
    pub combat_player_score: u32,
    #[prost(uint32, tag = "16")]
    pub damage_dealt_to_objectives: u32,
    #[prost(uint32, tag = "17")]
    pub damage_dealt_to_turrets: u32,
    #[prost(uint32, tag = "18")]
    pub damage_self_mitigated: u32,
    #[prost(uint32, tag = "19")]
    pub deaths: u32,
    #[prost(uint32, tag = "20")]
    pub double_kills: u32,
    #[prost(uint32, tag = "21")]
    pub gold_earned: u32,
    #[prost(uint32, tag = "22")]
    pub gold_spent: u32,
    #[prost(uint32, tag = "23")]
    pub inhibitor_kills: u32,
    #[prost(uint32, tag = "24")]
    pub item0: u32,
    #[prost(uint32, tag = "25")]
    pub item1: u32,
    #[prost(uint32, tag = "26")]
    pub item2: u32,
    #[prost(uint32, tag = "27")]
    pub item3: u32,
    #[prost(uint32, tag = "28")]
    pub item4: u32,
    #[prost(uint32, tag = "29")]
    pub item5: u32,
    #[prost(uint32, tag = "30")]
    pub item6: u32,
    #[prost(uint32, tag = "31")]
    pub killing_sprees: u32,
    #[prost(uint32, tag = "32")]
    pub kills: u32,
    #[prost(uint32, tag = "33")]
    pub largest_critical_strike: u32,
    #[prost(uint32, tag = "34")]
    pub largest_killing_spree: u32,
    #[prost(uint32, tag = "35")]
    pub largest_multi_kill: u32,
    #[prost(uint32, tag = "36")]
    pub longest_time_spent_living: u32,
    #[prost(uint32, tag = "37")]
    pub magic_damage_dealt: u32,
    #[prost(uint32, tag = "38")]
    pub magic_damage_dealt_to_champions: u32,
    #[prost(uint32, tag = "39")]
    pub magical_damage_taken: u32,
    #[prost(uint32, tag = "40")]
    pub neutral_minions_killed: u32,
    #[prost(uint32, tag = "41")]
    pub neutral_minions_killed_enemy_jungle: u32,
    #[prost(uint32, tag = "42")]
    pub neutral_minions_killed_team_jungle: u32,
    #[prost(uint32, tag = "43")]
    pub objective_player_score: u32,
    #[prost(uint32, tag = "44")]
    pub participant_id: u32,
    #[prost(uint32, tag = "45")]
    pub penta_kills: u32,
    #[prost(uint32, tag = "46")]
    pub perk0: u32,
    #[prost(uint32, tag = "47")]
    pub perk1: u32,
    #[prost(uint32, tag = "48")]
    pub perk2: u32,
    #[prost(uint32, tag = "49")]
    pub perk3: u32,
    #[prost(uint32, tag = "50")]
    pub perk4: u32,
    #[prost(uint32, tag = "51")]
    pub perk5: u32,
    #[prost(uint32, tag = "52")]
    pub perk_primary_style: u32,
    #[prost(uint32, tag = "53")]
    pub perk_sub_style: u32,
    #[prost(uint32, tag = "54")]
    pub physical_damage_dealt: u32,
    #[prost(uint32, tag = "55")]
    pub physical_damage_dealt_to_champions: u32,
    #[prost(uint32, tag = "56")]
    pub physical_damage_taken: u32,
    #[prost(uint32, tag = "57")]
    pub player_score0: u32,
    #[prost(uint32, tag = "58")]
    pub player_score1: u32,
    #[prost(uint32, tag = "59")]
    pub player_score2: u32,
    #[prost(uint32, tag = "60")]
    pub player_score3: u32,
    #[prost(uint32, tag = "61")]
    pub player_score4: u32,
    #[prost(uint32, tag = "62")]
    pub player_score5: u32,
    #[prost(uint32, tag = "63")]
    pub player_score6: u32,
    #[prost(uint32, tag = "64")]
    pub player_score7: u32,
    #[prost(uint32, tag = "65")]
    pub player_score8: u32,
    #[prost(uint32, tag = "66")]
    pub player_score9: u32,
    #[prost(uint32, tag = "67")]
    pub quadra_kills: u32,
    #[prost(uint32, tag = "68")]
    pub sight_wards_bought_in_game: u32,
    #[prost(uint32, tag = "69")]
    pub subteam_placement: u32,
    #[prost(uint32, tag = "70")]
    pub time_c_cing_others: u32,
    #[prost(uint32, tag = "71")]
    pub total_damage_dealt: u32,
    #[prost(uint32, tag = "72")]
    pub total_damage_dealt_to_champions: u32,
    #[prost(uint32, tag = "73")]
    pub total_damage_taken: u32,
    #[prost(uint32, tag = "74")]
    pub total_heal: u32,
    #[prost(uint32, tag = "75")]
    pub total_minions_killed: u32,
    #[prost(uint32, tag = "76")]
    pub total_player_score: u32,
    #[prost(uint32, tag = "77")]
    pub total_score_rank: u32,
    #[prost(uint32, tag = "78")]
    pub total_time_crowd_control_dealt: u32,
    #[prost(uint32, tag = "79")]
    pub total_units_healed: u32,
    #[prost(uint32, tag = "80")]
    pub triple_kills: u32,
    #[prost(uint32, tag = "81")]
    pub true_damage_dealt: u32,
    #[prost(uint32, tag = "82")]
    pub true_damage_dealt_to_champions: u32,
    #[prost(uint32, tag = "83")]
    pub true_damage_taken: u32,
    #[prost(uint32, tag = "84")]
    pub turret_kills: u32,
    #[prost(uint32, tag = "85")]
    pub unreal_kills: u32,
    #[prost(uint32, tag = "86")]
    pub vision_score: u32,
    #[prost(uint32, tag = "87")]
    pub vision_wards_bought_in_game: u32,
    #[prost(uint32, tag = "88")]
    pub wards_killed: u32,
    #[prost(uint32, tag = "89")]
    pub wards_placed: u32,
    #[prost(uint32, tag = "90")]
    pub player_augment1: u32,
    #[prost(uint32, tag = "91")]
    pub player_augment2: u32,
    #[prost(uint32, tag = "92")]
    pub player_augment3: u32,
    #[prost(uint32, tag = "93")]
    pub player_augment4: u32,
    #[prost(uint32, tag = "94")]
    pub player_augment5: u32,
    #[prost(uint32, tag = "95")]
    pub player_augment6: u32,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[serde(rename_all = "camelCase")]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ParticipantIdentity {
    #[prost(uint32, tag = "1")]
    pub participant_id: u32,
    #[prost(message, optional, tag = "2")]
    pub player: ::core::option::Option<Player>,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[serde(rename_all = "camelCase")]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ParticipantIdentityTuple {
    #[prost(uint32, tag = "1")]
    pub participant_id: u32,
    #[prost(string, tag = "2")]
    pub puuid: ::prost::alloc::string::String,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[serde(rename_all = "camelCase")]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Player {
    #[prost(uint32, tag = "1")]
    pub profile_icon: u32,
    #[prost(uint64, tag = "2")]
    pub account_id: u64,
    #[prost(uint64, tag = "3")]
    pub current_account_id: u64,
    #[prost(uint64, tag = "4")]
    pub summoner_id: u64,
    #[prost(string, tag = "5")]
    pub current_platform_id: ::prost::alloc::string::String,
    #[prost(string, tag = "6")]
    pub platform_id: ::prost::alloc::string::String,
    #[prost(string, tag = "7")]
    pub match_history_uri: ::prost::alloc::string::String,
    #[prost(string, tag = "8")]
    pub puuid: ::prost::alloc::string::String,
    #[prost(string, tag = "9")]
    pub game_name: ::prost::alloc::string::String,
    #[prost(string, tag = "10")]
    pub tag_line: ::prost::alloc::string::String,
    #[prost(string, tag = "11")]
    pub summoner_name: ::prost::alloc::string::String,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[serde(rename_all = "camelCase")]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Players {
    #[prost(message, repeated, tag = "1")]
    pub players: ::prost::alloc::vec::Vec<Player>,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[serde(rename_all = "camelCase")]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Timeline {
    #[prost(uint32, tag = "1")]
    pub participant_id: u32,
    #[prost(string, tag = "2")]
    pub lane: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub role: ::prost::alloc::string::String,
    #[prost(map = "string, float", tag = "4")]
    pub creeps_per_min_deltas: ::std::collections::HashMap<
        ::prost::alloc::string::String,
        f32,
    >,
    #[prost(map = "string, float", tag = "5")]
    pub cs_diff_per_min_deltas: ::std::collections::HashMap<
        ::prost::alloc::string::String,
        f32,
    >,
    #[prost(map = "string, float", tag = "6")]
    pub damage_taken_diff_per_min_deltas: ::std::collections::HashMap<
        ::prost::alloc::string::String,
        f32,
    >,
    #[prost(map = "string, float", tag = "7")]
    pub damage_taken_per_min_deltas: ::std::collections::HashMap<
        ::prost::alloc::string::String,
        f32,
    >,
    #[prost(map = "string, float", tag = "8")]
    pub gold_per_min_deltas: ::std::collections::HashMap<
        ::prost::alloc::string::String,
        f32,
    >,
    #[prost(map = "string, float", tag = "9")]
    pub xp_diff_per_min_deltas: ::std::collections::HashMap<
        ::prost::alloc::string::String,
        f32,
    >,
    #[prost(map = "string, float", tag = "10")]
    pub xp_per_min_deltas: ::std::collections::HashMap<
        ::prost::alloc::string::String,
        f32,
    >,
}
