// This file is @generated by prost-build.
#[derive(serde::Serialize, serde::Deserialize)]
#[serde(rename_all = "camelCase")]
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct RerollPoints {
    #[prost(int32, tag = "1")]
    pub current_points: i32,
    #[prost(int32, tag = "2")]
    pub max_rolls: i32,
    #[prost(int32, tag = "3")]
    pub number_of_rolls: i32,
    #[prost(int32, tag = "4")]
    pub points_cost_to_roll: i32,
    #[prost(int32, tag = "5")]
    pub points_to_reroll: i32,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[serde(rename_all = "camelCase")]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SummonerBaseInfo {
    #[prost(bool, tag = "1")]
    pub unnamed: bool,
    #[prost(bool, tag = "2")]
    pub name_change_flag: bool,
    #[prost(int64, tag = "3")]
    pub account_id: i64,
    #[prost(int32, tag = "4")]
    pub percent_complete_for_next_level: i32,
    #[prost(int32, tag = "5")]
    pub profile_icon_id: i32,
    #[prost(int64, tag = "6")]
    pub summoner_id: i64,
    #[prost(int32, tag = "7")]
    pub summoner_level: i32,
    #[prost(int64, tag = "8")]
    pub xp_since_last_level: i64,
    #[prost(int64, tag = "9")]
    pub xp_until_next_level: i64,
    #[prost(string, tag = "10")]
    pub display_name: ::prost::alloc::string::String,
    #[prost(string, tag = "11")]
    pub game_name: ::prost::alloc::string::String,
    #[prost(string, tag = "12")]
    pub internal_name: ::prost::alloc::string::String,
    #[prost(string, tag = "13")]
    pub privacy: ::prost::alloc::string::String,
    #[prost(string, tag = "14")]
    pub puuid: ::prost::alloc::string::String,
    #[prost(string, tag = "15")]
    pub tag_line: ::prost::alloc::string::String,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[serde(rename_all = "camelCase")]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SummonerInfoRaw {
    #[prost(message, optional, tag = "1")]
    pub base: ::core::option::Option<SummonerBaseInfo>,
    #[prost(message, optional, tag = "2")]
    pub reroll_points: ::core::option::Option<RerollPoints>,
}
