// This file is @generated by prost-build.
#[derive(serde::Serialize, serde::Deserialize)]
#[serde(rename_all = "camelCase")]
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct PhaseWithSummonerId {
    #[prost(enumeration = "GameflowPhaseEnum", tag = "1")]
    pub phase: i32,
    #[prost(uint64, tag = "2")]
    pub summoner_id: u64,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[serde(rename_all = "camelCase")]
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum GameflowPhaseEnum {
    /// 正在匹配
    Matchmaking = 0,
    /// 英雄选择中
    ChampSelect = 1,
    /// 等待接受状态中
    ReadyCheck = 2,
    /// 游戏进行中
    InProgress = 3,
    /// 游戏结算
    EndOfGame = 4,
    /// 房间
    Lobby = 5,
    /// 游戏开始
    GameStart = 6,
    /// 无
    None = 7,
    /// 重新连接
    Reconnect = 8,
    /// 等待结果
    WaitingForStats = 9,
    /// 结束游戏之前
    PreEndOfGame = 10,
    /// 在观战中
    WatchInProgress = 11,
}
impl GameflowPhaseEnum {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Matchmaking => "Matchmaking",
            Self::ChampSelect => "ChampSelect",
            Self::ReadyCheck => "ReadyCheck",
            Self::InProgress => "InProgress",
            Self::EndOfGame => "EndOfGame",
            Self::Lobby => "Lobby",
            Self::GameStart => "GameStart",
            Self::None => "None",
            Self::Reconnect => "Reconnect",
            Self::WaitingForStats => "WaitingForStats",
            Self::PreEndOfGame => "PreEndOfGame",
            Self::WatchInProgress => "WatchInProgress",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "Matchmaking" => Some(Self::Matchmaking),
            "ChampSelect" => Some(Self::ChampSelect),
            "ReadyCheck" => Some(Self::ReadyCheck),
            "InProgress" => Some(Self::InProgress),
            "EndOfGame" => Some(Self::EndOfGame),
            "Lobby" => Some(Self::Lobby),
            "GameStart" => Some(Self::GameStart),
            "None" => Some(Self::None),
            "Reconnect" => Some(Self::Reconnect),
            "WaitingForStats" => Some(Self::WaitingForStats),
            "PreEndOfGame" => Some(Self::PreEndOfGame),
            "WatchInProgress" => Some(Self::WatchInProgress),
            _ => None,
        }
    }
}
