// This file is @generated by prost-build.
#[derive(serde::Serialize, serde::Deserialize)]
#[serde(rename_all = "camelCase")]
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct SimpleLocalMember {
    #[prost(bool, tag = "1")]
    pub is_leader: bool,
    #[prost(int64, tag = "2")]
    pub summoner_id: i64,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[serde(rename_all = "camelCase")]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SimpleLobbyInfo {
    #[prost(string, tag = "1")]
    pub party_id: ::prost::alloc::string::String,
    #[prost(map = "int64, message", tag = "2")]
    pub member_map: ::std::collections::HashMap<i64, SimpleLocalMember>,
}
