// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.2.0
//   protoc               v5.28.3
/* eslint-disable */
export * as gameflow from "./index.lcu.gameflow";
export * as lobby from "./index.lcu.lobby";
export * as matchHistory from "./index.lcu.matchHistory";
export * as summoner from "./index.lcu.summoner";
