// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.2.0
//   protoc               v5.28.3
// source: rest/user.proto
/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import { gameflowPhaseEnumFromJSON, gameflowPhaseEnumToJSON } from "../lcu/gameflow";
import { SummonerInfoRaw } from "../lcu/summoner";
function createBaseSummonerState() {
    return { phase: 0, info: undefined };
}
export const SummonerState = {
    encode(message, writer = new BinaryWriter()) {
        if (message.phase !== 0) {
            writer.uint32(8).int32(message.phase);
        }
        if (message.info !== undefined) {
            SummonerInfoRaw.encode(message.info, writer.uint32(18).fork()).join();
        }
        return writer;
    },
    decode(input, length) {
        const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
        let end = length === undefined ? reader.len : reader.pos + length;
        const message = createBaseSummonerState();
        while (reader.pos < end) {
            const tag = reader.uint32();
            switch (tag >>> 3) {
                case 1:
                    if (tag !== 8) {
                        break;
                    }
                    message.phase = reader.int32();
                    continue;
                case 2:
                    if (tag !== 18) {
                        break;
                    }
                    message.info = SummonerInfoRaw.decode(reader, reader.uint32());
                    continue;
            }
            if ((tag & 7) === 4 || tag === 0) {
                break;
            }
            reader.skip(tag & 7);
        }
        return message;
    },
    fromJSON(object) {
        return {
            phase: isSet(object.phase) ? gameflowPhaseEnumFromJSON(object.phase) : 0,
            info: isSet(object.info) ? SummonerInfoRaw.fromJSON(object.info) : undefined,
        };
    },
    toJSON(message) {
        const obj = {};
        if (message.phase !== 0) {
            obj.phase = gameflowPhaseEnumToJSON(message.phase);
        }
        if (message.info !== undefined) {
            obj.info = SummonerInfoRaw.toJSON(message.info);
        }
        return obj;
    },
    create(base) {
        return SummonerState.fromPartial(base ?? {});
    },
    fromPartial(object) {
        const message = createBaseSummonerState();
        message.phase = object.phase ?? 0;
        message.info = (object.info !== undefined && object.info !== null)
            ? SummonerInfoRaw.fromPartial(object.info)
            : undefined;
        return message;
    },
};
function createBaseSummonerStates() {
    return { states: [] };
}
export const SummonerStates = {
    encode(message, writer = new BinaryWriter()) {
        for (const v of message.states) {
            SummonerState.encode(v, writer.uint32(10).fork()).join();
        }
        return writer;
    },
    decode(input, length) {
        const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
        let end = length === undefined ? reader.len : reader.pos + length;
        const message = createBaseSummonerStates();
        while (reader.pos < end) {
            const tag = reader.uint32();
            switch (tag >>> 3) {
                case 1:
                    if (tag !== 10) {
                        break;
                    }
                    message.states.push(SummonerState.decode(reader, reader.uint32()));
                    continue;
            }
            if ((tag & 7) === 4 || tag === 0) {
                break;
            }
            reader.skip(tag & 7);
        }
        return message;
    },
    fromJSON(object) {
        return {
            states: globalThis.Array.isArray(object?.states) ? object.states.map((e) => SummonerState.fromJSON(e)) : [],
        };
    },
    toJSON(message) {
        const obj = {};
        if (message.states?.length) {
            obj.states = message.states.map((e) => SummonerState.toJSON(e));
        }
        return obj;
    },
    create(base) {
        return SummonerStates.fromPartial(base ?? {});
    },
    fromPartial(object) {
        const message = createBaseSummonerStates();
        message.states = object.states?.map((e) => SummonerState.fromPartial(e)) || [];
        return message;
    },
};
function isSet(value) {
    return value !== null && value !== undefined;
}
